# Generated by Django 5.2.8 on 2025-11-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
