# Generated by Django 5.2.8 on 2025-11-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0002_alter_libro_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
