# Generated by Django 5.2.8 on 2025-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0003_rename_stock_libro_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='precio',
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 10:00:00', verbose_name='Fecha de Publicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(default='Sinopsis pendiente de carga'),
            preserve_default=False,
        ),
    ]
