# Generated by Django 5.2.8 on 2025-11-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0004_remove_libro_cantidad_remove_libro_precio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], verbose_name='Puntuación')),
                ('texto', models.TextField(verbose_name='Contenido de la Reseña')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='appInicial.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
