# Generated by Django 5.2.8 on 2025-11-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0006_libro_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resena',
            old_name='Libro',
            new_name='libro',
        ),
    ]
