# Generated by Django 5.2.8 on 2025-11-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0007_rename_libro_resena_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
