# Generated by Django 5.2.8 on 2025-11-21 15:12

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0008_libro_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('libro', 'usuario')},
        ),
    ]
