# Generated by Django 5.2.8 on 2025-11-24 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInicial', '0010_anuncio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
